[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tauon-optimizer"
version = "0.1.4"
description = "Fast Muon-like optimizer with AdamW speed"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["tauon*"]